name: Manually trigger for deploy to Firebase
on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'
      - name: Install frontend dependencies
        run: cd frontend && npm i && npm run build:prod
      - name: Copy fronend to public firabase structure
        run: cp -a frontend/dist-public/. public/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      
